const CFG={ID:'SPREADSHEET_ID',PEPPER:'PASSWORD_PEPPER',TTL:21600,EMP:'DSCNV',S:{ADM:'AdminUsers',SUR:'Surveys',SEC:'SurveySections',QUE:'Questions',OPT:'QuestionOptions',RULE:'QuestionRules',RES:'SurveyResponses',ANS:'SurveyAnswers',AUD:'AuditLog'}};
const TYPES=['text','textarea','number','date','datetime','email','phone','select','radio','multiselect','checkbox','yesno','rating5','rating10','likert5'];
function doGet(){return out({ok:true,service:'RASOAT Survey Platform',version:'3.0'})}
function doPost(e){try{let b=JSON.parse(e.postData.contents||'{}'),a=b.action;let f={getPublicSurvey,getSurvey:getPublicSurvey,employeeLogin,saveResponse,adminLogin,adminLogout,adminBootstrap,adminGetSurvey,adminSaveSurvey,adminCreateSurvey,adminCloneSurvey,adminSetSurveyStatus,adminSaveQuestion,adminDeleteQuestion,adminSaveRule,adminDeleteRule,adminDashboard,adminGetResponses,adminGetResponseDetail,adminGetQuestionBank,adminAddToQuestionBank,adminChangePassword,adminExportCsv,setupSystem};if(!f[a])return out({ok:false,error:'INVALID_ACTION'});return out(f[a](b))}catch(e){return out({ok:false,error:'SERVER_ERROR',message:err(e)})}}
function setupSystem(){let ss=ss_();ensure(ss,CFG.EMP,['MaNV','HoTen','CCCD']);ensure(ss,CFG.S.ADM,['Username','PasswordHash','PasswordSalt','Role','Active','CreatedAt','UpdatedAt']);ensure(ss,CFG.S.SUR,['SurveyId','Code','Name','Title','Description','WelcomeText','ConsentText','Status','StartAt','EndAt','Version','CreatedAt','CreatedBy','UpdatedAt','UpdatedBy']);ensure(ss,CFG.S.SEC,['SectionId','SurveyId','Title','Description','SortOrder','Active','UpdatedAt']);ensure(ss,CFG.S.QUE,['QuestionId','SurveyId','SectionId','FieldKey','Label','Type','Required','Placeholder','HelpText','DefaultValue','ValidationJson','SortOrder','Active','BankTag','UpdatedAt','UpdatedBy']);ensure(ss,CFG.S.OPT,['OptionId','QuestionId','Value','Label','SortOrder','Active','UpdatedAt']);ensure(ss,CFG.S.RULE,['RuleId','SurveyId','SourceQuestionId','Operator','CompareValue','Action','TargetQuestionId','Active','UpdatedAt']);ensure(ss,CFG.S.RES,['ResponseId','SurveyId','SurveyVersion','MaNV','HoTen','CCCD','Status','Consent','StartedAt','SubmittedAt','UpdatedAt']);ensure(ss,CFG.S.ANS,['AnswerId','ResponseId','SurveyId','QuestionId','FieldKey','ValueText','ValueNumber','ValueDate','ValueJson','UpdatedAt']);ensure(ss,CFG.S.AUD,['AuditId','At','ActorType','Actor','Action','EntityType','EntityId','DetailJson']);let p=PropertiesService.getScriptProperties();if(!p.getProperty(CFG.PEPPER))p.setProperty(CFG.PEPPER,hex_(64));let ad=sh_(CFG.S.ADM);if(ad.getLastRow()<2){let salt=hex_(32);ad.appendRow(['admin',hash_('ChangeMe@123',salt),salt,'SUPER_ADMIN',true,new Date(),new Date()])}if(sh_(CFG.S.SUR).getLastRow()<2)seed_();return {ok:true,message:'Setup completed',version:'3.0'}}
function seed_(){let now=new Date(),id='SV_'+uuid_(),ss=sh_(CFG.S.SUR);ss.appendRow([id,'KSTT_2026','Khảo sát hiện tại','KHẢO SÁT THU THẬP THÔNG TIN','Có thể thay đổi trong Admin.','Vui lòng kiểm tra thông tin.','Tôi đồng ý cho Công ty thu thập và xử lý dữ liệu.','PUBLISHED',now,new Date('2026-12-31T23:59:59'),1,now,'setup',now,'setup']);let sec=sh_(CFG.S.SEC),a='SEC_'+uuid_(),b='SEC_'+uuid_();sec.getRange(2,1,2,7).setValues([[a,id,'Thông tin cá nhân','',10,true,now],[b,id,'Thông tin khác','',20,true,now]]);let q=sh_(CFG.S.QUE),qs=[['Q_'+uuid_(),id,a,'ngay_sinh','Ngày sinh','date',true,'','','','{}',10,true,'',now,'setup'],['Q_'+uuid_(),id,a,'gioi_tinh','Giới tính','radio',true,'','','','{}',20,true,'',now,'setup'],['Q_'+uuid_(),id,a,'dan_toc','Dân tộc','text',false,'Nhập dân tộc','','','{}',30,true,'',now,'setup'],['Q_'+uuid_(),id,b,'dia_chi','Địa chỉ thường trú','textarea',true,'','','','{}',40,true,'',now,'setup'],['Q_'+uuid_(),id,b,'mien_giam','Trường hợp miễn/giảm','multiselect',false,'','','','{}',50,true,'',now,'setup']];q.getRange(2,1,qs.length,16).setValues(qs);let om=sh_(CFG.S.OPT),gioi=qs[1][0],mien=qs[4][0],o=[];['Nam','Nữ','Khác'].forEach((x,i)=>o.push(['OPT_'+uuid_(),gioi,x,x,i+1,true,now]));['Không thuộc trường hợp miễn/giảm','Trẻ em','Người cao tuổi','Người khuyết tật','Hộ nghèo/cận nghèo','Khác'].forEach((x,i)=>o.push(['OPT_'+uuid_(),mien,x,x,i+1,true,now]));om.getRange(2,1,o.length,7).setValues(o)}
function getPublicSurvey(b){let s=surveyCode_(b.code||'KSTT_2026');if(!s)return {ok:false,error:'SURVEY_NOT_FOUND',message:'Không tìm thấy khảo sát.'};if(String(s.Status)!=='PUBLISHED'||!window_(s))return {ok:false,error:'SURVEY_CLOSED',message:'Khảo sát chưa mở hoặc đã đóng.'};return {ok:true,survey:pub_(s),sections:sections_(s.SurveyId),questions:questions_(s.SurveyId),rules:rules_(s.SurveyId)}}
function employeeLogin(b){let c=norm_(b.cccd);if(!/^\d{9,12}$/.test(c))return {ok:false,message:'CCCD không hợp lệ.'};let s=surveyCode_(b.code||'KSTT_2026'),e=employees_().find(x=>norm_(x.CCCD)===c);if(!s||String(s.Status)!=='PUBLISHED'||!window_(s))return {ok:false,error:'SURVEY_CLOSED',message:'Khảo sát chưa mở hoặc đã đóng.'};if(!e)return {ok:false,error:'NOT_FOUND',message:'Không tìm thấy nhân viên.'};let t=session_('employee',{maNV:e.MaNV,hoTen:e.HoTen,cccd:c,surveyId:s.SurveyId}),r=latest_(s.SurveyId,e.MaNV);return {ok:true,token:t,employee:{maNV:e.MaNV,hoTen:e.HoTen,cccd:c},answers:r?answers_(r.ResponseId):{},response:r?{ResponseId:r.ResponseId,Status:r.Status}:null,survey:pub_(s),sections:sections_(s.SurveyId),questions:questions_(s.SurveyId),rules:rules_(s.SurveyId)}}
function saveResponse(b){let z=sess_(b.token);if(!z||z.type!=='employee')return {ok:false,error:'UNAUTHORIZED',message:'Phiên hết hạn.'};let s=getSurvey_(z.payload.surveyId);if(!s||String(s.Status)!=='PUBLISHED'||!window_(s))return {ok:false,error:'SURVEY_CLOSED',message:'Khảo sát đã đóng.'};let a=b.answers||{},qs=questions_(s.SurveyId);for(let q of qs)if(q.Required&&empty_(a[q.QuestionId]))return {ok:false,error:'REQUIRED',message:'Vui lòng điền: '+q.Label};let old=latest_(s.SurveyId,z.payload.maNV),now=new Date(),rid=old?old.ResponseId:Utilities.getUuid(),o={ResponseId:rid,SurveyId:s.SurveyId,SurveyVersion:s.Version,MaNV:z.payload.maNV,HoTen:z.payload.hoTen,CCCD:z.payload.cccd,Status:'COMPLETED',Consent:b.consent?'Đồng ý':'',StartedAt:old?old.StartedAt:now,SubmittedAt:now,UpdatedAt:now};upsert_(CFG.S.RES,o,'ResponseId');replaceAnswers_(rid,s.SurveyId,qs,a,now);audit_('EMPLOYEE',z.payload.maNV,'SUBMIT','Response',rid,{});drop_(b.token);return {ok:true,message:'Đã lưu khảo sát thành công.'}}
function adminLogin(b){let a=admin_(String(b.username||'')),p=String(b.password||'');if(!a||!active_(a.Active)||!eq_(hash_(p,a.PasswordSalt),a.PasswordHash))return {ok:false,error:'INVALID_LOGIN',message:'Tài khoản hoặc mật khẩu không đúng.'};let t=session_('admin',{username:a.Username,role:a.Role});audit_('ADMIN',a.Username,'LOGIN','Admin',a.Username,{});return {ok:true,token:t,user:{username:a.Username,role:a.Role}}}
function adminLogout(b){drop_(b.token);return {ok:true}}
function adminBootstrap(b){let u=auth_(b.token);if(!u)return unauth_();return {ok:true,user:u,surveys:allSurveys_().map(pub_),questionTypes:TYPES}}
function adminGetSurvey(b){if(!auth_(b.token))return unauth_();let s=surveyCode_(b.code);if(!s)return {ok:false,error:'SURVEY_NOT_FOUND'};return {ok:true,survey:pub_(s),sections:sections_(s.SurveyId),questions:questions_(s.SurveyId),rules:rules_(s.SurveyId)}}
function adminSaveSurvey(b){let u=auth_(b.token),s=surveyCode_(b.code);if(!u)return unauth_();if(!s)return {ok:false,error:'SURVEY_NOT_FOUND'};let h=map_(sh_(CFG.S.SUR)),p=b.patch||{};['Name','Title','Description','WelcomeText','ConsentText','StartAt','EndAt','Version'].forEach(k=>{if(p[k]!==undefined)sh_(CFG.S.SUR).getRange(s._row,h[k]+1).setValue(k==='Version'?Number(p[k]||1):p[k])});sh_(CFG.S.SUR).getRange(s._row,h.UpdatedAt+1).setValue(new Date());sh_(CFG.S.SUR).getRange(s._row,h.UpdatedBy+1).setValue(u.username);return {ok:true}}
function adminCreateSurvey(b){let u=auth_(b.token),x=b.survey||{},code=String(x.Code||'').trim().toUpperCase().replace(/\s+/g,'_');if(!u)return unauth_();if(!/^[A-Z0-9_-]{2,80}$/.test(code)||surveyCode_(code))return {ok:false,error:'INVALID_CODE',message:'Mã trùng hoặc không hợp lệ.'};let id='SV_'+uuid_(),n=new Date();sh_(CFG.S.SUR).appendRow([id,code,x.Name||code,x.Title||code,x.Description||'',x.WelcomeText||'',x.ConsentText||'','DRAFT',x.StartAt||'',x.EndAt||'',1,n,u.username,n,u.username]);return {ok:true,code}}
function adminCloneSurvey(b){let u=auth_(b.token),s=surveyCode_(b.sourceCode),code=String(b.newCode||'').trim().toUpperCase();if(!u||!s)return !u?unauth_():{ok:false,error:'NOT_FOUND'};if(surveyCode_(code))return {ok:false,error:'DUPLICATE_CODE'};let n='SV_'+uuid_(),now=new Date();sh_(CFG.S.SUR).appendRow([n,code,s.Name+' - Copy',s.Title,s.Description,s.WelcomeText,s.ConsentText,'DRAFT',s.StartAt,s.EndAt,Number(s.Version||1)+1,now,u.username,now,u.username]);let sm={};sections_(s.SurveyId).forEach(x=>{let id='SEC_'+uuid_();sm[x.SectionId]=id;sh_(CFG.S.SEC).appendRow([id,n,x.Title,x.Description,x.SortOrder,true,now])});let qm={};questions_(s.SurveyId).forEach(q=>{let id='Q_'+uuid_();qm[q.QuestionId]=id;sh_(CFG.S.QUE).appendRow([id,n,sm[q.SectionId]||'',q.FieldKey,q.Label,q.Type,q.Required,q.Placeholder,q.HelpText,q.DefaultValue,JSON.stringify(q.Validation||{}),q.SortOrder,true,q.BankTag,now,u.username]);replaceOptions_(id,q.Options,now)});rules_(s.SurveyId).forEach(r=>sh_(CFG.S.RULE).appendRow(['RULE_'+uuid_(),n,qm[r.SourceQuestionId]||'',r.Operator,r.CompareValue,r.Action,qm[r.TargetQuestionId]||'',true,now]));return {ok:true,code}}
function adminSetSurveyStatus(b){let u=auth_(b.token),s=surveyCode_(b.code);if(!u)return unauth_();if(!s)return {ok:false};let st=String(b.status||'').toUpperCase();if(!['DRAFT','PUBLISHED','CLOSED','ARCHIVED'].includes(st))return {ok:false,error:'INVALID_STATUS'};let h=map_(sh_(CFG.SUR));sh_(CFG.SUR).getRange(s._row,h.Status+1).setValue(st);return {ok:true}}
function adminSaveQuestion(b){let u=auth_(b.token),s=surveyCode_(b.code),q=b.question||{};if(!u)return unauth_();if(!s)return {ok:false,error:'SURVEY_NOT_FOUND'};if(!TYPES.includes(String(q.Type||'text')))return {ok:false,error:'INVALID_TYPE'};let sh=sh_(CFG.S.QUE),h=map_(sh),id=String(q.QuestionId||''),row=id?find_(sh,h.QuestionId,id):-1,now=new Date();if(row<2){id='Q_'+uuid_();sh.appendRow([id,s.SurveyId,q.SectionId||'',q.FieldKey||slug_(q.Label),q.Label,q.Type||'text',!!q.Required,q.Placeholder||'',q.HelpText||'',q.DefaultValue||'',JSON.stringify(q.Validation||{}),Number(q.SortOrder)||999,true,q.BankTag||'',now,u.username])}else{let v={SectionId:q.SectionId,FieldKey:q.FieldKey||slug_(q.Label),Label:q.Label,Type:q.Type,Required:!!q.Required,Placeholder:q.Placeholder||'',HelpText:q.HelpText||'',DefaultValue:q.DefaultValue||'',ValidationJson:JSON.stringify(q.Validation||{}),SortOrder:Number(q.SortOrder)||999,Active:q.Active!==false,UpdatedAt:now,UpdatedBy:u.username};Object.keys(v).forEach(k=>sh.getRange(row,h[k]+1).setValue(v[k]))}if(Array.isArray(q.Options))replaceOptions_(id,q.Options,now);return {ok:true,questionId:id}}
function adminDeleteQuestion(b){let u=auth_(b.token);if(!u)return unauth_();let sh=sh_(CFG.S.QUE),h=map_(sh),r=find_(sh,h.QuestionId,b.questionId);if(r<2)return {ok:false};sh.getRange(r,h.Active+1).setValue(false);return {ok:true}}
function adminSaveRule(b){let u=auth_(b.token);if(!u)return unauth_();let s=surveyCode_(b.code),r=b.rule||{};if(!s)return {ok:false};sh_(CFG.S.RULE).appendRow(['RULE_'+uuid_(),s.SurveyId,r.SourceQuestionId,r.Operator||'equals',r.CompareValue||'',r.Action||'show',r.TargetQuestionId,true,new Date()]);return {ok:true}}
function adminDeleteRule(b){let u=auth_(b.token);if(!u)return unauth_();let sh=sh_(CFG.S.RULE),h=map_(sh),r=find_(sh,h.RuleId,b.ruleId);if(r<2)return {ok:false};sh.getRange(r,h.Active+1).setValue(false);return {ok:true}}
function adminDashboard(b){let u=auth_(b.token),s=surveyCode_(b.code);if(!u)return unauth_();if(!s)return {ok:false};let em=employees_(),rs=responses_(s.SurveyId),latest={};rs.forEach(r=>{if(!latest[r.MaNV]||date_(r.UpdatedAt)>date_(latest[r.MaNV].UpdatedAt))latest[r.MaNV]=r});let sum={total:em.length,completed:0,inProgress:0,notStarted:0,refused:0},rows=em.map(e=>{let r=latest[e.MaNV],st=r?r.Status:'NOT_STARTED';if(st==='COMPLETED')sum.completed++;else if(st==='REFUSED')sum.refused++;else if(st==='IN_PROGRESS')sum.inProgress++;else sum.notStarted++;return {maNV:e.MaNV,hoTen:e.HoTen,cccd:mask_(e.CCCD),status:st,updatedAt:r?fmt_(r.UpdatedAt):''}});return {ok:true,summary:sum,rows,survey:pub_(s)}}
function adminGetResponses(b){let u=auth_(b.token),s=surveyCode_(b.code);if(!u)return unauth_();if(!s)return {ok:false};let q=String(b.search||'').toLowerCase(),st=String(b.status||''),rows=responses_(s.SurveyId).filter(r=>(!st||r.Status===st)&&(!q||String(r.MaNV).toLowerCase().includes(q)||String(r.HoTen).toLowerCase().includes(q)));return {ok:true,rows:rows.map(r=>({ResponseId:r.ResponseId,MaNV:r.MaNV,HoTen:r.HoTen,CCCD:mask_(r.CCCD),Status:r.Status,SubmittedAt:dateISO_(r.SubmittedAt),UpdatedAt:dateISO_(r.UpdatedAt)}))}}
function adminGetResponseDetail(b){let u=auth_(b.token);if(!u)return unauth_();let r=findResponse_(b.responseId);if(!r)return {ok:false,error:'NOT_FOUND'};return {ok:true,response:r,questions:questions_(r.SurveyId),answers:answers_(r.ResponseId)}}
function adminGetQuestionBank(b){let u=auth_(b.token);if(!u)return unauth_();return {ok:true,rows:allQuestions_().filter(q=>q.BankTag)}}
function adminAddToQuestionBank(b){let u=auth_(b.token);if(!u)return unauth_();let sh=sh_(CFG.S.QUE),h=map_(sh),r=find_(sh,h.QuestionId,b.questionId);if(r<2)return {ok:false};sh.getRange(r,h.BankTag+1).setValue(b.tag||'General');return {ok:true}}
function adminChangePassword(b){let u=auth_(b.token);if(!u)return unauth_();let a=admin_(u.username),nw=String(b.newPassword||'');if(nw.length<10||nw!==String(b.confirmPassword||''))return {ok:false,message:'Mật khẩu mới tối thiểu 10 ký tự và phải khớp.'};if(!eq_(hash_(String(b.oldPassword||''),a.PasswordSalt),a.PasswordHash))return {ok:false,message:'Mật khẩu hiện tại không đúng.'};let salt=hex_(32),h=map_(sh_(CFG.S.ADM));sh_(CFG.S.ADM).getRange(a._row,h.PasswordHash+1).setValue(hash_(nw,salt));sh_(CFG.S.ADM).getRange(a._row,h.PasswordSalt+1).setValue(salt);return {ok:true}}
function adminExportCsv(b){let u=auth_(b.token),s=surveyCode_(b.code);if(!u)return unauth_();let qs=questions_(s.SurveyId),lines=[['MaNV','HoTen','CCCD','Status','SubmittedAt'].concat(qs.map(q=>q.Label)).map(csv).join(',')];responses_(s.SurveyId).forEach(r=>{let a=answers_(r.ResponseId);lines.push([r.MaNV,r.HoTen,r.CCCD,r.Status,fmt_(r.SubmittedAt)].concat(qs.map(q=>Array.isArray(a[q.QuestionId])?a[q.QuestionId].join('; '):(a[q.QuestionId]||''))).map(csv).join(','))});return {ok:true,filename:s.Code+'.csv',data:Utilities.base64Encode(Utilities.newBlob('\ufeff'+lines.join('\r\n'),'text/csv').getBytes())}}
function sections_(id){return data_(CFG.S.SEC).filter(r=>String(r.SurveyId)===String(id)&&active_(r.Active)).map(r=>({SectionId:r.SectionId,SurveyId:r.SurveyId,Title:r.Title,Description:r.Description,SortOrder:+r.SortOrder||999})).sort((a,b)=>a.SortOrder-b.SortOrder)}
function questions_(id){return data_(CFG.S.QUE).filter(r=>String(r.SurveyId)===String(id)&&active_(r.Active)).map(r=>({QuestionId:r.QuestionId,SurveyId:r.SurveyId,SectionId:r.SectionId,FieldKey:r.FieldKey,Label:r.Label,Type:r.Type,Required:active_(r.Required),Placeholder:r.Placeholder,HelpText:r.HelpText,DefaultValue:r.DefaultValue,Validation:tryJson_(r.ValidationJson),SortOrder:+r.SortOrder||999,Options:opts_(r.QuestionId),BankTag:r.BankTag})).sort((a,b)=>a.SortOrder-b.SortOrder)}
function rules_(id){return data_(CFG.S.RULE).filter(r=>String(r.SurveyId)===String(id)&&active_(r.Active)).map(r=>({RuleId:r.RuleId,SourceQuestionId:r.SourceQuestionId,Operator:r.Operator,CompareValue:r.CompareValue,Action:r.Action,TargetQuestionId:r.TargetQuestionId}))}
function opts_(id){return data_(CFG.S.OPT).filter(r=>String(r.QuestionId)===String(id)&&active_(r.Active)).map(r=>({OptionId:r.OptionId,Value:r.Value,Label:r.Label,SortOrder:+r.SortOrder||999})).sort((a,b)=>a.SortOrder-b.SortOrder)}
function allQuestions_(){let a=[];allSurveys_().forEach(s=>a=a.concat(questions_(s.SurveyId)));return a}
function allSurveys_(){return data_(CFG.S.SUR)}
function surveyCode_(c){return allSurveys_().find(x=>String(x.Code).trim()===String(c).trim())||null}
function getSurvey_(id){return allSurveys_().find(x=>String(x.SurveyId)===String(id))||null}
function responses_(id){return data_(CFG.S.RES).filter(r=>String(r.SurveyId)===String(id))}
function latest_(sid,ma){return responses_(sid).filter(r=>String(r.MaNV)===String(ma)).sort((a,b)=>date_(b.UpdatedAt)-date_(a.UpdatedAt))[0]||null}
function findResponse_(id){let r=null;allSurveys_().some(s=>{r=responses_(s.SurveyId).find(x=>String(x.ResponseId)===String(id));return !!r});return r}
function answers_(rid){let o={};data_(CFG.S.ANS).filter(r=>String(r.ResponseId)===String(rid)).forEach(r=>{if(r.ValueJson){o[r.QuestionId]=tryJson_(r.ValueJson)}else if(r.ValueNumber!=='')o[r.QuestionId]=r.ValueNumber;else if(r.ValueDate!=='')o[r.QuestionId]=dateISO_(r.ValueDate);else o[r.QuestionId]=r.ValueText||''});return o}
function replaceAnswers_(rid,sid,qs,a,now){let sh=sh_(CFG.S.ANS),h=map_(sh),rows=sh.getDataRange().getValues(),keep=[rows[0]];for(let i=1;i<rows.length;i++)if(String(rows[i][h.ResponseId])!==String(rid))keep.push(rows[i]);sh.clearContents();sh.getRange(1,1,keep.length,keep[0].length).setValues(keep);let out=[];qs.forEach(q=>{let v=a[q.QuestionId];if(empty_(v))return;let row=new Array(Object.keys(h).length).fill('');row[h.AnswerId]='ANS_'+uuid_();row[h.ResponseId]=rid;row[h.SurveyId]=sid;row[h.QuestionId]=q.QuestionId;row[h.FieldKey]=q.FieldKey;if(Array.isArray(v))row[h.ValueJson]=JSON.stringify(v);else if(q.Type==='number'&&isFinite(Number(v)))row[h.ValueNumber]=Number(v);else if(['date','datetime'].includes(q.Type)&&v)row[h.ValueDate]=new Date(v);else row[h.ValueText]=String(v).slice(0,5000);row[h.UpdatedAt]=now;out.push(row)});if(out.length)sh.getRange(sh.getLastRow()+1,1,out.length,Object.keys(h).length).setValues(out)}
function employees_(){let c=CacheService.getScriptCache(),x=c.get('emp3');if(x)try{return JSON.parse(x)}catch(e){}let sh=sh_(CFG.EMP),v=sh.getDataRange().getDisplayValues(),h=employeeMap_(v[0]),a=v.slice(1).map(r=>({MaNV:r[h.MaNV]||'',HoTen:r[h.HoTen]||'',CCCD:norm_(r[h.CCCD])})).filter(x=>x.MaNV||x.HoTen||x.CCCD);c.put('emp3',JSON.stringify(a),300);return a}
function employeeMap_(a){let h={};a.forEach((v,i)=>h[String(v).trim()]=i);if(h.MaNV===undefined)h.MaNV=h['Mã NV'];if(h.HoTen===undefined)h.HoTen=h['Họ tên']??h['Họ và tên'];if(h.CCCD===undefined)h.CCCD=h['Số CCCD']??h['CCCD'];if([h.MaNV,h.HoTen,h.CCCD].some(x=>x===undefined))throw Error('DSCNV cần MaNV, HoTen, CCCD');return h}
function data_(n){let s=sh_(n),v=s.getDataRange().getValues();if(v.length<2)return[];let h=map_(s);return v.slice(1).map((r,i)=>{let o={_row:i+2};Object.keys(h).forEach(k=>o[k]=r[h[k]]);return o})}
function admin_(u){return data_(CFG.S.ADM).find(a=>String(a.Username)===u)||null}
function session_(type,p){let t=Utilities.getUuid()+'-'+Utilities.getUuid();CacheService.getScriptCache().put('s:'+t,JSON.stringify({type,payload:p,exp:Date.now()+CFG.TTL*1000}),CFG.TTL);return t}
function sess_(t){let x=t&&CacheService.getScriptCache().get('s:'+t);if(!x)return null;try{let o=JSON.parse(x);if(o.exp<Date.now()){drop_(t);return null}return o}catch(e){return null}}
function drop_(t){if(t)CacheService.getScriptCache().remove('s:'+t)}function auth_(t){let s=sess_(t);return s&&s.type==='admin'?s.payload:null}function unauth_(){return {ok:false,error:'UNAUTHORIZED',message:'Phiên Admin hết hạn.'}}
function ss_(){let id=PropertiesService.getScriptProperties().getProperty(CFG.ID);if(!id)throw Error('Chưa cấu hình SPREADSHEET_ID trong Script Properties.');return SpreadsheetApp.openById(id)}
function sh_(n){let s=ss_().getSheetByName(n);if(!s)throw Error('Thiếu sheet '+n+'. Hãy chạy setupSystem().');return s}
function ensure(ss,n,h){let s=ss.getSheetByName(n)||ss.insertSheet(n);if(s.getLastRow()===0)s.getRange(1,1,1,h.length).setValues([h]);s.setFrozenRows(1)}function map_(s){let a=s.getRange(1,1,1,s.getLastColumn()).getDisplayValues()[0],o={};a.forEach((v,i)=>{if(v)o[v]=i});return o}function find_(s,c,v){let n=s.getLastRow()-1;if(n<1)return-1;let a=s.getRange(2,c+1,n,1).getDisplayValues();for(let i=0;i<a.length;i++)if(String(a[i][0])===String(v))return i+2;return-1}
function upsert_(sn,o,key,val){let s=sh_(sn),h=map_(s),r=find_(s,h[key],val);if(r<2)r=s.getLastRow()+1;let a=new Array(Object.keys(h).length).fill('');Object.keys(o).forEach(k=>{if(h[k]!==undefined)a[h[k]]=o[k]});s.getRange(r,1,1,a.length).setValues([a])}
function replaceOptions_(qid,arr,now){let s=sh_(CFG.S.OPT),h=map_(s),v=s.getDataRange().getValues(),keep=[v[0]];for(let i=1;i<v.length;i++)if(String(v[i][h.QuestionId])!==String(qid))keep.push(v[i]);s.clearContents();s.getRange(1,1,keep.length,keep[0].length).setValues(keep);let a=arr.map((o,i)=>['OPT_'+uuid_(),qid,typeof o==='object'?o.Value:o,typeof o==='object'?(o.Label||o.Value):o,i+1,true,now]);if(a.length)s.getRange(s.getLastRow()+1,1,a.length,7).setValues(a)}
function pub_(s){return {SurveyId:s.SurveyId,Code:s.Code,Name:s.Name,Title:s.Title,Description:s.Description,WelcomeText:s.WelcomeText,ConsentText:s.ConsentText,Status:s.Status,StartAt:dateISO_(s.StartAt),EndAt:dateISO_(s.EndAt),Version:+s.Version||1}}
function active_(v){return v===true||String(v).toLowerCase()==='true'||String(v)==='1'}function window_(s){let n=Date.now(),a=date_(s.StartAt),b=date_(s.EndAt);return(!a||n>=a)&&(!b||n<=b)}function empty_(v){return Array.isArray(v)?v.length===0:String(v??'').trim()===''}function norm_(v){return String(v??'').replace(/\D/g,'').slice(0,12)}function mask_(v){let s=norm_(v);return s.length>4?'*'.repeat(s.length-4)+s.slice(-4):'*'.repeat(s.length)}function date_(v){let d=v instanceof Date?v:new Date(v);return isNaN(d)?0:d.getTime()}function dateISO_(v){if(!v)return'';let d=v instanceof Date?v:new Date(v);return isNaN(d)?String(v):d.toISOString()}function fmt_(v){return dateISO_(v)}function err(e){return String(e&&e.message||e).slice(0,700)}function uuid_(){return Utilities.getUuid().slice(0,8).toUpperCase()}function hex_(n){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,Utilities.getUuid()+Math.random()).map(x=>('0'+(x<0?x+256:x).toString(16)).slice(-2)).join('').slice(0,n)}function hash_(p,s){let pepper=PropertiesService.getScriptProperties().getProperty(CFG.PEPPER)||'';return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,p+':'+s+':'+pepper).map(x=>('0'+(x<0?x+256:x).toString(16)).slice(-2)).join('')}function eq_(a,b){return String(a)===String(b)}function tryJson_(x){try{return x?JSON.parse(x):{}}catch(e){return {}}}function slug_(s){return String(s||'field').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D').toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'').slice(0,80)||'field'}function csv(v){return '"'+String(v??'').replace(/"/g,'""')+'"'}function out(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON)}function audit_(a,b,c,d,e,f){try{sh_(CFG.S.AUD).appendRow([Utilities.getUuid(),new Date(),a,b,c,d,e,JSON.stringify(f||{})])}catch(x){}}
